import type { Player, Game, Debt, Transaction, DashboardStats, Command, Workspace, Chat } from './types';

export const mockPlayers: Player[] = [
  {
    id: '1',
    name: 'João Silva',
    email: 'joao.silva@email.com',
    phone: '(11) 98765-4321',
    cpf: '123.456.789-00',
    status: 'active',
    balance: -150.0,
    totalDebt: 150.0,
    joinDate: '2024-01-15',
    lastActivity: '2024-11-10',
  },
  {
    id: '2',
    name: 'Maria Santos',
    email: 'maria.santos@email.com',
    phone: '(11) 98765-1234',
    cpf: '987.654.321-00',
    status: 'active',
    balance: 0,
    totalDebt: 0,
    joinDate: '2024-02-20',
    lastActivity: '2024-11-11',
  },
  {
    id: '3',
    name: 'Pedro Oliveira',
    email: 'pedro.oliveira@email.com',
    phone: '(11) 98765-5678',
    cpf: '456.789.123-00',
    status: 'active',
    balance: -300.0,
    totalDebt: 300.0,
    joinDate: '2024-03-10',
    lastActivity: '2024-11-09',
  },
  {
    id: '4',
    name: 'Ana Costa',
    email: 'ana.costa@email.com',
    phone: '(11) 98765-9012',
    cpf: '789.123.456-00',
    status: 'inactive',
    balance: -50.0,
    totalDebt: 50.0,
    joinDate: '2024-04-05',
    lastActivity: '2024-10-15',
  },
  {
    id: '5',
    name: 'Carlos Ferreira',
    email: 'carlos.ferreira@email.com',
    phone: '(11) 98765-3456',
    cpf: '321.654.987-00',
    status: 'suspended',
    balance: -500.0,
    totalDebt: 500.0,
    joinDate: '2024-01-20',
    lastActivity: '2024-09-20',
  },
];

export const mockGames: Game[] = [
  {
    id: '1',
    name: 'Pelada Sábado',
    type: 'futebol',
    date: '2024-11-16',
    time: '09:00',
    location: 'Campo do Parque Central',
    maxPlayers: 20,
    currentPlayers: 16,
    pricePerPlayer: 50.0,
    status: 'scheduled',
    createdBy: 'admin',
    createdAt: '2024-11-01',
  },
  {
    id: '2',
    name: 'Futebol de Domingo',
    type: 'futebol',
    date: '2024-11-17',
    time: '10:00',
    location: 'Arena Esportiva',
    maxPlayers: 22,
    currentPlayers: 22,
    pricePerPlayer: 60.0,
    status: 'scheduled',
    createdBy: 'admin',
    createdAt: '2024-11-02',
  },
  {
    id: '3',
    name: 'Rachão de Terça',
    type: 'futebol',
    date: '2024-11-12',
    time: '19:00',
    location: 'Quadra Coberta',
    maxPlayers: 14,
    currentPlayers: 14,
    pricePerPlayer: 40.0,
    status: 'completed',
    createdBy: 'admin',
    createdAt: '2024-10-28',
  },
  {
    id: '4',
    name: 'Basquete Quinta',
    type: 'basquete',
    date: '2024-11-14',
    time: '20:00',
    location: 'Ginásio Municipal',
    maxPlayers: 10,
    currentPlayers: 8,
    pricePerPlayer: 30.0,
    status: 'completed',
    createdBy: 'admin',
    createdAt: '2024-10-30',
  },
  {
    id: '5',
    name: 'Vôlei Sexta',
    type: 'volei',
    date: '2024-11-15',
    time: '18:00',
    location: 'Clube Recreativo',
    maxPlayers: 12,
    currentPlayers: 6,
    pricePerPlayer: 35.0,
    status: 'cancelled',
    createdBy: 'admin',
    createdAt: '2024-11-03',
  },
];

export const mockDebts: Debt[] = [
  {
    id: '1',
    playerId: '1',
    playerName: 'João Silva',
    gameId: '1',
    gameName: 'Pelada Sábado',
    amount: 50.0,
    dueDate: '2024-11-20',
    status: 'pending',
    createdAt: '2024-11-01',
  },
  {
    id: '2',
    playerId: '1',
    playerName: 'João Silva',
    gameId: '3',
    gameName: 'Rachão de Terça',
    amount: 40.0,
    dueDate: '2024-11-15',
    status: 'overdue',
    createdAt: '2024-10-28',
  },
  {
    id: '3',
    playerId: '3',
    playerName: 'Pedro Oliveira',
    gameId: '1',
    gameName: 'Pelada Sábado',
    amount: 50.0,
    dueDate: '2024-11-20',
    status: 'pending',
    createdAt: '2024-11-01',
  },
  {
    id: '4',
    playerId: '3',
    playerName: 'Pedro Oliveira',
    gameId: '2',
    gameName: 'Futebol de Domingo',
    amount: 60.0,
    dueDate: '2024-11-22',
    status: 'pending',
    createdAt: '2024-11-02',
  },
  {
    id: '5',
    playerId: '3',
    playerName: 'Pedro Oliveira',
    gameId: '3',
    gameName: 'Rachão de Terça',
    amount: 40.0,
    dueDate: '2024-11-15',
    status: 'overdue',
    createdAt: '2024-10-28',
  },
  {
    id: '6',
    playerId: '5',
    playerName: 'Carlos Ferreira',
    gameId: '3',
    gameName: 'Rachão de Terça',
    amount: 40.0,
    dueDate: '2024-11-15',
    status: 'overdue',
    createdAt: '2024-10-28',
  },
  {
    id: '7',
    playerId: '2',
    playerName: 'Maria Santos',
    gameId: '3',
    gameName: 'Rachão de Terça',
    amount: 40.0,
    dueDate: '2024-11-15',
    status: 'paid',
    createdAt: '2024-10-28',
    paidAt: '2024-11-12',
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    playerId: '2',
    playerName: 'Maria Santos',
    type: 'payment',
    amount: 40.0,
    description: 'Pagamento - Rachão de Terça',
    date: '2024-11-12',
    status: 'completed',
  },
  {
    id: '2',
    playerId: '1',
    playerName: 'João Silva',
    type: 'debt',
    amount: -50.0,
    description: 'Débito - Pelada Sábado',
    date: '2024-11-01',
    status: 'pending',
  },
  {
    id: '3',
    playerId: '3',
    playerName: 'Pedro Oliveira',
    type: 'debt',
    amount: -60.0,
    description: 'Débito - Futebol de Domingo',
    date: '2024-11-02',
    status: 'pending',
  },
];

export const mockDashboardStats: DashboardStats = {
  totalPlayers: 45,
  activePlayers: 38,
  totalGames: 24,
  upcomingGames: 5,
  totalDebt: 1250.0,
  paidThisMonth: 3840.0,
  revenue: 15680.0,
  revenueGrowth: 12.5,
};

export const mockCommands: Command[] = [
  {
    id: '1',
    name: 'Adicionar Jogador',
    description: 'Adiciona um novo jogador ao sistema',
    command: '/add-player',
    category: 'player',
    parameters: [
      { name: 'nome', type: 'string', required: true, description: 'Nome completo do jogador' },
      { name: 'email', type: 'string', required: true, description: 'Email do jogador' },
      { name: 'telefone', type: 'string', required: true, description: 'Telefone do jogador' },
      { name: 'cpf', type: 'string', required: false, description: 'CPF do jogador' },
    ],
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
    executionCount: 45,
  },
  {
    id: '2',
    name: 'Criar Jogo',
    description: 'Cria um novo jogo/evento',
    command: '/create-game',
    category: 'game',
    parameters: [
      { name: 'nome', type: 'string', required: true, description: 'Nome do jogo' },
      { name: 'data', type: 'date', required: true, description: 'Data do jogo' },
      { name: 'hora', type: 'string', required: true, description: 'Horário do jogo' },
      { name: 'local', type: 'string', required: true, description: 'Local do jogo' },
      { name: 'valor', type: 'number', required: true, description: 'Valor por jogador' },
      { name: 'max_jogadores', type: 'number', required: false, description: 'Máximo de jogadores', defaultValue: 20 },
    ],
    createdAt: '2024-01-15',
    updatedAt: '2024-02-10',
    executionCount: 24,
  },
  {
    id: '3',
    name: 'Registrar Pagamento',
    description: 'Registra o pagamento de um débito',
    command: '/register-payment',
    category: 'debt',
    parameters: [
      { name: 'jogador_id', type: 'string', required: true, description: 'ID do jogador' },
      { name: 'debito_id', type: 'string', required: true, description: 'ID do débito' },
      { name: 'valor', type: 'number', required: true, description: 'Valor pago' },
      { name: 'observacoes', type: 'string', required: false, description: 'Observações do pagamento' },
    ],
    createdAt: '2024-01-15',
    updatedAt: '2024-03-05',
    executionCount: 87,
  },
  {
    id: '4',
    name: 'Listar Devedores',
    description: 'Lista todos os jogadores com débitos pendentes',
    command: '/list-debtors',
    category: 'report',
    parameters: [
      { name: 'status', type: 'string', required: false, description: 'Status do débito (pending/overdue)', defaultValue: 'all' },
      { name: 'ordernar_por', type: 'string', required: false, description: 'Campo para ordenação', defaultValue: 'valor' },
    ],
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
    executionCount: 156,
  },
  {
    id: '5',
    name: 'Enviar Lembrete',
    description: 'Envia lembrete de pagamento para jogadores',
    command: '/send-reminder',
    category: 'system',
    parameters: [
      { name: 'jogador_id', type: 'string', required: false, description: 'ID do jogador (vazio = todos)' },
      { name: 'mensagem', type: 'string', required: false, description: 'Mensagem personalizada' },
    ],
    createdAt: '2024-01-20',
    updatedAt: '2024-01-20',
    executionCount: 34,
  },
];

export const mockWorkspaces: Workspace[] = [
  {
    id: '1',
    name: 'WhatsApp Principal',
    description: 'Workspace principal para grupos de futebol',
    platform: 'whatsapp',
    status: 'active',
    totalChats: 8,
    activeChats: 6,
    createdAt: '2024-01-15',
    lastSync: '2024-11-13 14:30',
    apiKey: 'whatsapp_abc123xyz',
  },
  {
    id: '2',
    name: 'Telegram Sports',
    description: 'Grupos de telegram para vários esportes',
    platform: 'telegram',
    status: 'active',
    totalChats: 4,
    activeChats: 3,
    createdAt: '2024-02-01',
    lastSync: '2024-11-13 14:15',
    apiKey: 'telegram_def456uvw',
  },
  {
    id: '3',
    name: 'Discord Community',
    description: 'Servidor Discord em manutenção',
    platform: 'discord',
    status: 'maintenance',
    totalChats: 2,
    activeChats: 0,
    createdAt: '2024-03-10',
    lastSync: '2024-11-10 10:00',
    apiKey: 'discord_ghi789rst',
  },
];

export const mockChats: Chat[] = [
  {
    id: '1',
    workspaceId: '1',
    name: 'Pelada Sábado - Parque Central',
    chatId: 'wsp_chat_001',
    label: 'Sábado 09:00',
    type: 'group',
    status: 'active',
    memberCount: 24,
    schedule: {
      weekday: 6,
      time: '09:00',
      title: 'Pelada Sábado',
      priceCents: 5000,
      pix: 'admin@botfut.com',
    },
    lastMessage: 'Confirmado para sábado!',
    lastMessageAt: '2024-11-13 10:30',
    createdAt: '2024-01-20',
    updatedAt: '2024-11-13',
  },
  {
    id: '2',
    workspaceId: '1',
    name: 'Futebol Domingo - Arena',
    chatId: 'wsp_chat_002',
    label: 'Domingo 10:00',
    type: 'group',
    status: 'active',
    memberCount: 28,
    schedule: {
      weekday: 0,
      time: '10:00',
      title: 'Futebol Domingo',
      priceCents: 6000,
      pix: 'admin@botfut.com',
    },
    lastMessage: 'Quem confirma para domingo?',
    lastMessageAt: '2024-11-13 12:15',
    createdAt: '2024-01-22',
    updatedAt: '2024-11-13',
  },
  {
    id: '3',
    workspaceId: '1',
    name: 'Rachão Terça - Quadra Coberta',
    chatId: 'wsp_chat_003',
    label: 'Terça 19:00',
    type: 'group',
    status: 'active',
    memberCount: 18,
    schedule: {
      weekday: 2,
      time: '19:00',
      title: 'Rachão Terça',
      priceCents: 4000,
      pix: 'admin@botfut.com',
    },
    lastMessage: 'Lista fechada!',
    lastMessageAt: '2024-11-12 18:45',
    createdAt: '2024-02-01',
    updatedAt: '2024-11-12',
  },
  {
    id: '4',
    workspaceId: '1',
    name: 'Pelada Quinta - Ginásio',
    chatId: 'wsp_chat_004',
    type: 'group',
    status: 'active',
    memberCount: 16,
    schedule: {
      weekday: 4,
      time: '20:00',
      title: 'Pelada Quinta',
      priceCents: 3500,
      pix: 'admin@botfut.com',
    },
    lastMessage: 'Faltam 4 vagas',
    lastMessageAt: '2024-11-13 08:00',
    createdAt: '2024-02-15',
    updatedAt: '2024-11-13',
  },
  {
    id: '5',
    workspaceId: '1',
    name: 'Grupo Geral - Avisos',
    chatId: 'wsp_chat_005',
    type: 'group',
    status: 'active',
    memberCount: 45,
    lastMessage: 'Atenção: mudança de horário!',
    lastMessageAt: '2024-11-12 15:30',
    createdAt: '2024-01-15',
    updatedAt: '2024-11-12',
  },
  {
    id: '6',
    workspaceId: '1',
    name: 'Arquivado - Vôlei Antigo',
    chatId: 'wsp_chat_006',
    type: 'group',
    status: 'archived',
    memberCount: 12,
    lastMessage: 'Grupo encerrado',
    lastMessageAt: '2024-09-30 10:00',
    createdAt: '2024-05-01',
    updatedAt: '2024-09-30',
  },
  {
    id: '7',
    workspaceId: '2',
    name: 'Telegram - Pelada Sabado',
    chatId: 'tg_chat_001',
    label: 'Sábado 08:00',
    type: 'group',
    status: 'active',
    memberCount: 20,
    schedule: {
      weekday: 6,
      time: '08:00',
      title: 'Pelada Telegram',
      priceCents: 4500,
      pix: 'admin@botfut.com',
    },
    lastMessage: 'Confirmados: 18/20',
    lastMessageAt: '2024-11-13 11:00',
    createdAt: '2024-02-10',
    updatedAt: '2024-11-13',
  },
  {
    id: '8',
    workspaceId: '2',
    name: 'Telegram - Basquete Quinta',
    chatId: 'tg_chat_002',
    label: 'Quinta 19:00',
    type: 'group',
    status: 'active',
    memberCount: 12,
    schedule: {
      weekday: 4,
      time: '19:00',
      title: 'Basquete',
      priceCents: 3000,
      pix: 'admin@botfut.com',
    },
    lastMessage: 'Jogo confirmado!',
    lastMessageAt: '2024-11-13 09:30',
    createdAt: '2024-03-05',
    updatedAt: '2024-11-13',
  },
  {
    id: '9',
    workspaceId: '2',
    name: 'Telegram - Avisos Gerais',
    chatId: 'tg_chat_003',
    type: 'group',
    status: 'active',
    memberCount: 35,
    lastMessage: 'Novidades da semana',
    lastMessageAt: '2024-11-12 16:00',
    createdAt: '2024-02-01',
    updatedAt: '2024-11-12',
  },
  {
    id: '10',
    workspaceId: '3',
    name: 'Discord - Gaming Sports',
    chatId: 'dc_channel_001',
    type: 'group',
    status: 'inactive',
    memberCount: 8,
    lastMessage: 'Canal em manutenção',
    lastMessageAt: '2024-11-10 10:00',
    createdAt: '2024-03-15',
    updatedAt: '2024-11-10',
  },
];
